### ISSUE TITLE
Upload Links for Resume Review, DemoCamp, and Lightning Talks

### ISSUE THREAD

**Issue by VMS-6511** [cusec/2018#2]
**Links:**

- [ ] Resume Upload
Description: Send your resume to all our sponsors all in one click! To participate in the Resume Review, you should also submit your resume here.
I was hoping for something similar to last years:
https://script.google.com/a/macros/cusec.net/s/AKfycbwKZEz5LWogYT2npgRUAUa7Biy5Syi1mPntTYT1jvGHxFpe27E/exec

- [ ] DemoCamp
Description: Are you the next PiedPiper&trade; who is Mo-Lo-So? This is your chance to show everyone what you or your team have been working on!
Google Form: https://goo.gl/forms/GUC2wi9s4eAkIjMG2

- [ ] Lightning Talks:
Description: Share your ideas and thoughts on a topic of your choosing with the rest of the conference. For 5 mins you are the oracle.
I was hoping for something similar to last years: 
https://script.google.com/a/macros/cusec.net/s/AKfycbz7HwH28W_sgh-owA2hTxVX1rLtLnC4nj21lVL9e8b1OFx5utTQ/exec

Preferably on the front page if possible!

**Comment by kennyhong** [comment]
Completed
